# Generated by Django 5.0.4 on 2024-05-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
