# Generated by Django 5.0.4 on 2024-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploader',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.FileField(default=None, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_course',
            field=models.CharField(choices=[('CS101', 'CS101'), ('CS102', 'CS102'), ('HUM112', 'HUM112'), ('CS223', 'CS223'), ('CS224', 'CS224')], default='not selected', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
        migrations.DeleteModel(
            name='Kurs',
        ),
    ]
