# Generated by Django 5.0.4 on 2024-05-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        ('profiles', '0002_userprofile_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assesments',
            field=models.ManyToManyField(blank=True, to='instructor.assessment'),
        ),
    ]
