# Generated by Django 5.0.2 on 2024-05-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('instructor', '0004_attendance_grade_delete_user_and_more'),
        ('profiles', '0005_instructor_student_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ManyToManyField(blank=True, to='instructor.attendance'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.ManyToManyField(blank=True, to='instructor.grade'),
        ),
    ]
