# Generated by Django 5.0.2 on 2024-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_delete_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
