# Generated by Django 5.0.2 on 2024-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_remove_assessment_course_remove_attendance_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
